"""Type stub for the compiled ``veltix._rust`` extension (built by maturin).

This file only exists for type checkers. At runtime the extension is
optional: ``veltix.network._rust`` falls back to the pure-Python protocol
implementation when it is not installed, and ``VELTIX_DISABLE_RUST`` can
force the fallback.
"""

from typing import Any

__all__ = ["MessageBuffer", "compile", "parse"]

class MessageBuffer:
    """Accumulates TCP stream data and extracts complete framed messages."""

    def __init__(self, max_message_size: int, max_buffer_size: int = ...) -> None: ...
    def add_data(self, data: bytes) -> tuple[bool, str]: ...
    def extract_messages(self) -> list[tuple[str, Any]]: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    @property
    def max_message_size(self) -> int: ...
    @property
    def max_buffer_size(self) -> int: ...

def parse(data: bytes | bytearray, max_message_size: int) -> tuple[int, bytes, int, int, bytes]: ...
def compile(type_code: int, content: bytes, request_id: int, flags: int) -> bytes: ...
